// <auto-generated />
using CrudAPP.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudAPP.Migrations
{
    [DbContext(typeof(RabbitmqContext))]
    [Migration("20220126152434_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CrudAPP.BO.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cameroun",
                            ShortName = "CM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "France",
                            ShortName = "FR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Belgique",
                            ShortName = "BL"
                        });
                });

            modelBuilder.Entity("CrudAPP.BO.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Bastos Yaounde",
                            CountryId = 1,
                            Name = "Black & White",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Rue Jean France",
                            CountryId = 3,
                            Name = "Continental hotel",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Adress = "405 Boulevar de la paix",
                            CountryId = 2,
                            Name = "Blender Palace",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("CrudAPP.BO.Hotel", b =>
                {
                    b.HasOne("CrudAPP.BO.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
